# Generated by Django 6.0.5 on 2026-05-28 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('match_type', models.CharField(choices=[('T1', 'T1 - 1 Over'), ('T2', 'T2 - 2 Overs'), ('T5', 'T5 - 5 Overs'), ('T8', 'T8 - 8 Overs'), ('T10', 'T10 - 10 Overs'), ('T20', 'T20 - 20 Overs'), ('ODI', 'ODI - 50 Overs'), ('TEST', 'Test Match'), ('CUSTOM', 'Custom Overs')], max_length=20)),
                ('custom_overs', models.PositiveIntegerField(blank=True, help_text='Only required when match type is Custom', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Running', 'Running'), ('Completed', 'Completed')], default='Upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
