# Generated by Django 6.0.5 on 2026-05-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='match_type',
            field=models.CharField(choices=[('T1', 'T1 - 1 Over'), ('T2', 'T2 - 2 Overs'), ('T5', 'T5 - 5 Overs'), ('T10', 'T10 - 10 Overs'), ('T20', 'T20 - 20 Overs'), ('ODI', 'ODI - 50 Overs'), ('TEST', 'Test Match'), ('CUSTOM', 'Custom Overs')], max_length=20),
        ),
    ]
