# Generated by Django 6.0.5 on 2026-05-28 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_number', models.PositiveIntegerField(choices=[(1, '1st Innings'), (2, '2nd Innings')])),
                ('runs', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('legal_balls', models.PositiveIntegerField(default=0)),
                ('target', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='teams.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_innings', to='teams.team')),
                ('current_bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowler_innings', to='players.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='matches.match')),
                ('non_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_striker_innings', to='players.player')),
                ('striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='striker_innings', to='players.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BallByBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.PositiveIntegerField()),
                ('ball_number', models.PositiveIntegerField()),
                ('runs', models.PositiveIntegerField(default=0)),
                ('extra_type', models.CharField(choices=[('None', 'None'), ('Wide', 'Wide'), ('No Ball', 'No Ball'), ('Bye', 'Bye'), ('Leg Bye', 'Leg Bye')], default='None', max_length=20)),
                ('extra_runs', models.PositiveIntegerField(default=0)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wicket_type', models.CharField(choices=[('None', 'None'), ('Bowled', 'Bowled'), ('Caught', 'Caught'), ('LBW', 'LBW'), ('Run Out', 'Run Out'), ('Stumped', 'Stumped'), ('Hit Wicket', 'Hit Wicket')], default='None', max_length=20)),
                ('is_legal_ball', models.BooleanField(default=True)),
                ('commentary', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batsman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balls_faced', to='players.player')),
                ('bowler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balls_bowled', to='players.player')),
                ('out_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wickets_lost', to='players.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='scoring.innings')),
            ],
        ),
    ]
