# Generated by Django 6.0.5 on 2026-05-28 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All Rounder', 'All Rounder'), ('Wicket Keeper', 'Wicket Keeper')], max_length=30)),
                ('batting_style', models.CharField(choices=[('Right Hand Bat', 'Right Hand Bat'), ('Left Hand Bat', 'Left Hand Bat')], max_length=50)),
                ('bowling_style', models.CharField(choices=[('Right Arm Fast', 'Right Arm Fast'), ('Left Arm Fast', 'Left Arm Fast'), ('Right Arm Spin', 'Right Arm Spin'), ('Left Arm Spin', 'Left Arm Spin'), ('None', 'None')], max_length=50)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='player_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
